#!/bin/zsh
#
#
set -u -e -o pipefail

# doc: CMD -- Sets up pipewire.

if ! command -v pipewire; then
  tell "Installing pipewire"
  sudo xbps-install -S pipewire
fi

: "${XDG_CONFIG_HOME:=${HOME}/.config}"

if [[ ! -e "$XDG_CONFIG_HOME/pipewire" ]]; then
  tell "Creating directory: $XDG_CONFIG_HOME/pipewire"
  mkdir -p "${XDG_CONFIG_HOME}/pipewire/pipewire.conf.d"
fi

cd "$XDG_CONFIG_HOME/pipewire/pipewire.conf.d"
if [[ ! -e 10-wireplumber.conf ]]; then
  tell "Linking conf file..."
  ln -s /usr/share/examples/wireplumber/10-wireplumber.conf "$PWD/"
fi
