#!/bin/sh
#
#
set -u -e

do_update=""
for x in subuid subgid; do
  target="/etc/$x"
  origin="$HOME/config/root/etc_$x"
  ensure_exists "$origin"

  if diff "$origin" "$target"; then
    tell "Up-to-date: $target"
  else
    tell "Installing: $target ..."
    "$(which_do)" install -o root -g root "$origin" "$target"
    do_update="1"
  fi
done

if ! test -z "$do_update"; then
  check_podman_id_maps
fi
