#!/bin/sh
#
#
set -u -e

do_update=""
for x in subuid subgid; do
  target="/etc/$x"
  origin="$HOME/config/root/etc_$x"
  must_exist "$origin"

  if diff "$origin" "$target"; then
    tell "Up-to-date: $target"
  else
    tell "Installing: $target ..."
    "$(which_do)" install -o root -g root "$origin" "$target"
    do_update="yes"
  fi
done

[ "$do_update" = "" ] || check_podman_id_maps
