#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

if { ! command -v podman || ! command -v passwd; } >/dev/null ; then
  tell "Upgrading system..."
  sudo xbps-install -Su
  tell "Installing podman..."
  sudo xbps-install -S podman shadow passt
fi

sub_id_maps

output="$(sysctl user.max_user_namespaces | tr -d ' ' | cut -d'=' -f2)"
if test -z "$output" || [[ "$output" < 15017 ]] ; then
  err "sysctl user.max_user_namespaces is < 15017"
  exit 
fi

