#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD -- Upgrade Void packages.

cleanup

sudo xbps-install -Su || {
  sudo xbps-install -u xbps;
  sudo xbps-install -Su;
}

export NIXPKGS_ALLOW_UNFREE=1
nix-channel --update
nix-env -u

