#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD MAJOR_VERSION|18 - Using PGDG, setup postgresql. Default: 18.

pkg_name="postgresql"
pkg_version="${1:-18}"
pkg="${pkg_name}${pkg_version}"

tell "Setting up $pkg_name $pkg_version"

if dnf repolist --enabled | grep -i pgdg-common >/dev/null ; then
  tell "$pkg_name repo already installed."
else
  arch="$(uname -m)"
  repo_url="$(pgsql_repo)"
  tell "Installing PGDG repo: $repo_url ..."
  sudo dnf install "$repo_url"
fi

if rpm -q "$pkg" "$pkg"-server "$pkg"-libs ; then
  tell "Already installed: $pkg"
else
  tell "Installing ${pkg}..."
  sudo dnf install "$pkg" "$pkg"-server "$pkg"-libs
fi

