#!/bin/zsh
#
#
set -u -e -o pipefail

# doc: CMD -- Sets up $PGDATA directory if it is empty.

if ! id postgres; then
  user_postgres
fi

if [ ! -d "$PGDATA" ]; then
  tell "Creating $PGDATA"
  sudo mkdir -p "$PGDATA"
  sudo chown postgres:postgres "$PGDATA"
  sudo chmod 700 "$PGDATA"
fi

if [ -z "$(find "$PGDATA" -mindepth 1 -maxdepth 1 2>/dev/null)" ]; then
  tell "As postgres, initializing $PGDATA"
  sudo -u postgres "$DA_OS_BIN" initdb \
    --auth-local=peer   \
    --auth-host=reject  \
    --data-checksums    \
    --encoding=UTF8     \
    --locale=C.UTF-8    \
    -D "$PGDATA"
fi
