#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD -- Upserts system user postgres.
# doc:     Uses: PG_HOME

PG_HOME="${PG_HOME:-/home/postgres}"

# --------------------------------------------------------
# Create system group first, useradd does not create it.
if getent group postgres &>/dev/null ; then
  tell "postgres group exists."
else
  tell "Creating postgres group"
  sudo groupadd --system postgres
fi
# --------------------------------------------------------

# --------------------------------------------------------
# Create user:
if id "postgres" &>/dev/null  ; then
  tell "User already exists: postgres"
else
  tell "Creating user: postgres ..."
  sudo useradd \
    --system \
    --create-home \
    --home-dir "$PG_HOME" \
    --shell /sbin/nologin \
    --gid postgres \
    postgres
fi
# --------------------------------------------------------


getent passwd postgres
getent group  postgres
id postgres

ensure_perms 700 "$PG_HOME"
