# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer


host    all             all             127.0.0.1/32            reject
host    all             all             ::1/128                 reject


# Allow the local subnet (narrowly scoped) to connect using SCRAM
# Replace /24 with the exact mask if you only want a single IP.
host    all             all             100.1.1.0/24            scram-sha-256

# (Optional) Allow replication from a known replica IP only
# host    replication     replicator      100.1.1.21/32           scram-sha-256

# Explicitly reject other IPv4/IPv6 TCP connections (catch-all)
host    all             all             0.0.0.0/0               reject
host    all             all             ::0/0                   reject
