#!/bin/sh
#
#
set -u -e

set -x

if test -e "Caddyfile"; then
  target="Caddyfile"
else
  target="config/caddy/Caddyfile"
fi

ensure_exists "$target"
caddy fmt --overwrite "$target"
caddy validate --config "$target"
