#!/bin/sh
#
#
set -u -e

# doc: CMD 7xx DIR -- Upserts dir/file with right perms.

right_perms="$1"
target="$2"

ensure_exists "$target"

case "$(stat -c '%a' "$target")" in
"$right_perms")
  tell "$target is $right_perms"
  ;;

*)
  tell "Changing permissions of $target to ${right_perms}..."
  if is_owner "$USER" "$target"; then
    chmod "$right_perms" "$target"
  else
    if command -v sudo; then
      sudo chmod "$right_perms" "$target"
    fi

    if command -v doas; then
      sudo chmod "$right_perms" "$target"
    else
      err "No sudo or doas found."
      exit 1
    fi
  fi
  ;;
esac
