#!/bin/sh
#
#
set -u -e

# doc: CMD 7xx DIR -- Upserts dir/file with right perms.

right_perms="$1"
target="$2"

ensure_exists "$target"

case "$(stat -c '%a' "$target")" in
"$right_perms")
  tell "$target is $right_perms"
  exit 0
  ;;

*)
  tell "Changing permissions of $target to ${right_perms}..."
  if is_owner "$USER" "$target"; then
    chmod "$right_perms" "$target"
    exit 0
  fi

  if is_command sudo; then
    sudo chmod "$right_perms" "$target"
    exit 0
  fi

  if is_command doas; then
    doas chmod "$right_perms" "$target"
    exit 0
  fi

  err "No sudo or doas found."
  exit 1
  ;;
esac
