#!/bin/zsh
#
#
set -u -e -o pipefail

# doc: CMD  [owner|owner:group]  DIR  -- Exits 0 if owner of DIR == USERNAME. Exits 1 otherwise.

new_owner="$1"
target="$2"

ensure_exists "$target"

# current_owner="$(stat -c '%U' "$target")"
#
# [ "$current_owner" = "$new_owner" ]

case "$new_owner" in
*:*)
  current_owner="$(stat -c "%U:%G" "$target")"
  [[ "$new_owner" = "$current_owner" ]]
  ;;

*)
  current_owner="$(stat -c '%U' "$target")"
  [[ "$new_owner" = "$current_owner" ]]
  ;;
esac
