#!/bin/sh
#
set -u -e

# doc: CMD [...file paths]

for x in "$@"; do
  if test -e "$x"; then
    if test -L "$x"; then
      err "Symbolic link already exists: $x"
      exit 1
    fi

    if test -f "$x"; then
      err "File already exists: $x"
    fi

    if test -d "$x"; then
      err "Directory already exists: $x"
    fi

    exit 1
  fi
done
