#!/usr/bin/env sh
#
#
set -u -e


a="/etc/subuid"
b="/etc/subgid"

must_exist "$a"
must_exist "$b"

if ! diff "$a" "$b" ; then
  err "Files: do not match: $a != $b"
  exit 1
fi

awk -F: '!seen[$1]++ { print $1 }' /etc/subuid
