#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD [bin directory] [sub command] [..args]

bin_dir="$1"
shift

sub_cmd="$1"
shift

files="$(find "$bin_dir" -maxdepth 4 -type f -name "$sub_cmd")"

if test -z "$files" ; then
  err "!!! Unknown command: $sub_cmd $*"
  exit 1
fi

if [[ "$(echo files | wc -l)" = "1" ]]; then
  export BIN_DIR="$bin_dir"
  exec "$files" "$@"
  exit 0
fi

err "!!! Too many binaries found for command: $sub_cmd $*"
exit 1
