#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD [main cmd] [files or dirs paths...] 
# doc:      Prints doc: help strings.
# doc:      MAIN_CMD=basename of first argument.
#
main_cmd="${MAIN_CMD:-$(basename "$1")}"

{
  for x in "$@" ; do
    if test -f "$x" ; then
      printf '%s\0' "$x"
      continue
    fi
    find "$x" -mindepth 1 -maxdepth 1 -type f -print0 | sort -z
  done
} | xargs -0 grep -HE -- '# +doc:' | while read -r line ; do
  file="$(echo "$line" | cut -d':' -f1)"
  sub_cmd="$(basename "$file")"
  doc="$(echo "$line" | cut -d':' -f2-)"
  if [[ "$main_cmd" = "$sub_cmd" ]] ; then
    cmd="$main_cmd"
  else
    cmd="$main_cmd $sub_cmd"
  fi
  echo "$line" | sed 's/^[^:]\+:[[:space:]]*//; s/#[[:space:]]\+doc:// ; s/CMD/'${cmd}'/'
done
