#!/bin/sh
#
#
set -u -e

# doc: CMD (bin|opt) file/path

case "$*" in
'')
  err "$DA_SUB_CMD: No file path specified for new file."
  exit 2
  ;;

'opt '*)
  new_file="$2"
  da_os must_not_exist "$new_file"

  cat <<'EOF' >"$new_file"
#!/bin/sh
#
set -u -e

# doc: CMD (x|y)

case "\$#" in
    1)
    ;;

    2)
    ;;

    *)
      err "Unknown arguments for \$0: $*"
      exit 1
    ;;
esac
EOF
  chmod u+x "$new_file"
  ;;

'bin '*)
  new_file="$2"
  da_os must_not_exist "$new_file"

  cat <<'EOF' >"$new_file"
#!/bin/sh
#
set -u -e

# doc: CMD
EOF
  chmod u+x "$new_file"
  ;;

*)
  new_file="$1"
  da_os must_not_exist "$new_file"

  cat <<'EOF' >"$new_file"
#!/bin/sh
#
set -u -e

case "$*" in
# doc: CMD -- This help message.
"--help")
    da_os sh_help "$0"
  ;;

*)
  echo "!!! Unknown command: $*" >&2
  exit 1
  ;;
esac
EOF
  chmod u+x "$new_file"
  ;;
esac
