#!/bin/sh
#
#
set -u -e

# doc: CMD -- Prints out the main os and major version (if it exists).

while IFS='=' read -r key value; do
  case "$key" in
  ID)
    os_id=${value#\"}
    os_id=${os_id%\"}
    echo -n "$os_id "
    ;;
  VERSION_ID)
    version_id=${value#\"}
    version_id=${version_id%\"}
    version_major=${version_id%%.*}
    echo -n "$version_major"
    break
    ;;
  esac
done </etc/os-release

echo
