#!/usr/bin/env zsh
#
# doc: CMD -- Installs Caddyfile to a podman volume. (_data/)
#      CADDY_USER   = www-containers
#      CADDY_VOLUME = caddy-config

set -u -e -o pipefail

CADDY_USER="${CADDY_USER:-www-containers}"
CADDY_VOLUME="${CADDY_VOLUME:-caddy-config}"

origin="$HOME/config/caddy/Caddyfile"
must_exist "$origin"

target="$(caddy_get_volume_mount "$CADDY_USER" "$CADDY_VOLUME")/_data/Caddyfile"

tell "Checking Caddyfile: "

if ! doas diff "$origin" "$target" ; then
  tell "Installing Caddyfile: $target"
  doas install -m 0600 -o "$CADDY_USER" -g "$CADDY_USER" "$origin" "$target"
fi

# setup_service init.d/default "http_caddy" "$origin/initd.conf"
