#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

role="caddy"
origin="$HOME/config/caddy"
target="/var/lib/caddy"

ensure_dir "$origin"
ensure_bin rsync


tell "Checking Caddyfile..."
if ! doas diff "$origin/Caddyfile" "$target/Caddyfile" ; then
  tell "Installing Caddyfile"
  doas install -m 0644 -o root -g root "$origin/Caddyfile" "$target/Caddyfile"
fi

setup_service init.d/default "http_caddy" "$origin/initd.conf"
