#!/bin/sh
#
set -u -e

# doc: CMD  (USER)  dir/path

case "$#" in
1)
  target="$1"
  if ! test -d "$target"; then
    tell "Creating directory: $target ..."
    mkdir -p "$target"
  fi
  ;;

2)
  target_u="$1"
  target="$2"
  tell "Checking if $target exists for user $target_u"
  doas -u "$target_u" zsh -c "
    set -e -u -o pipefail
    if [[ ! -e '$target' ]] ; then
       echo '-- Creating $target for user $target_u ...' >&2
       mkdir -p '$target'
    fi
  "
  ;;

*)
  err "Unknown arguments for $0: $*"
  exit 1
  ;;
esac
