#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


if ! grep -E '^https.+/community' /etc/apk/repositories ; then
  err 'Enable community repository.'
  exit 1
fi

upgrade

tell "Installing podman-related packages..."
doas apk add podman crun fuse-overlayfs slirp4netns iptables

cgroups_setup

if ! id "containers" ; then
  tell "Setting up containers (non-root aacount)..."
  doas adduser -D -s /bin/sh containers
fi

if ! grep '^containers:' /etc/subuid /etc/subgid ; then
  tell "Setting up subordinate ID ranges for rootless user namespace mapping."
  doas touch /etc/subuid /etc/subgid
  printf '%s\n' 'containers:100000:65536' | doas tee -a /etc/subuid
  printf '%s\n' 'containers:100000:65536' | doas tee -a /etc/subgid
fi

tun_setup
