#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

if ! grep -E '^https.+/community' /etc/apk/repositories ; then
  err 'Enable community repository.'
  exit 1
fi

if ! is_command podman || ! is_command crun ; then
  upgrade
  tell "Installing podman-related packages..."
  doas apk add podman crun fuse-overlayfs slirp4netns iptables
fi

user_containers

cgroups_setup


sub_id_maps

# tun_setup
