#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

if ! grep -E '^https.+/community' /etc/apk/repositories ; then
  err 'Enable community repository.'
  exit 1
fi

if ! grep -q '^rc_cgroup_mode="unified"' /etc/rc.conf ; then
  err "/etc/rc.conf must have: rc_cgroup_mode=unified"
  exit 1
fi

upgrade

tell "Installing podman-related packages..."
doas apk add podman crun fuse-overlayfs slirp4netns iptables

if ! rc-service --exists cgroups ; then
  tell 'Adding service: cgroups'
  doas rc-update add cgroups
  tell 'Starting service: cgroups'
  doas rc-service cgroups start
fi

if ! modprobe tun ; then
  err "Failed: modprobe tun"
  exit 1
fi

target="/etc/modules-load.d/tun.conf"
if ! test -e "$target" ; then
  tell "Addig tun to /etc/modules"
  echo "tun" > tun.conf
  install -o root -g root tun.conf "$target"
fi


output="$(stat -fc %T /sys/fs/cgroup)"
case "$output" in
  cgroup2fs)
    :
    ;;
  *)
    err "/sys/fs/cgroup is not cgroup2fs. Try rebooting."
    exit 1
    ;;
esac


if ! grep '^containers:' /etc/subuid /etc/subgid ; then
  tell "Setting up containers non-root aacount..."
  doas adduser -D -s /bin/sh containers

  tell "Setting up subordinate ID ranges for rootless user namespace mapping."
  doas touch /etc/subuid /etc/subgid
  printf '%s\n' 'containers:100000:65536' | doas tee -a /etc/subuid
  printf '%s\n' 'containers:100000:65536' | doas tee -a /etc/subgid
fi

