#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

role="www_app"
origin="$HOME/config/caddy"
target="/home/$role/config/caddy"
tmp="/home/$role/tmp"

ensure_dir "$origin"
ensure_bin rsync

tell "Checking existence of: $tmp"
if ! doas test -d "$tmp" ; then
  tell "Creating: $tmp"
  doas -u "$role" mkdir "$tmp"
fi

tell "Checking existence of: $target"
if ! doas test -d "$target" ; then
  tell "Creating: $target"
  doas -u "$role" mkdir -p "$target"
fi

tell "Syncing files..."
doas rsync -avc --itemize-changes --chown="$role":"$role" "$origin/" "$target/"

setup_service init.d/default "http_caddy" "$origin/initd.conf"
