#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

if ! modprobe tun ; then
  err "Failed: modprobe tun"
  exit 1
fi

target="/etc/modules-load.d/tun.conf"
if ! test -e "$target" ; then
  tell "Addig tun to /etc/modules"
  cd "$DA_OS_DIR"
  mkdir -p tmp
  cd tmp
  echo "tun" > tun.conf
  doas install -o root -g root tun.conf "$target"
fi
