#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

new_user="containers"

! is_a_user "$new_user" || exit 0

tell "Creating system user: $new_user"
doas adduser -S -D -s /sbin/nologin "$new_user"

ensure_perms 700 "/home/$new_user"
