#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

new_user="www-containers"

if ! is_a_user "$new_user" ; then
  tell "Creating system user: $new_user"
  doas adduser -S -D -s /sbin/nologin "$new_user"
fi

ensure_perms 700 "/home/$new_user"
